### ISSUE TITLE
Regrow only tree stumps instead of all trees

### ISSUE THREAD

**Issue by danielwerg** [codengine/SOTFEdit#1]

**Comment by codengine** [comment]
I'll have a look into it. Should be doable I guess.

**Comment by danielwerg** [comment]
@codengine [This python script](https://gitlab.com/david-arppe/regrowstumpssonsoftheforest) does it, but I haven't tested it.

**Comment by codengine** [comment]
> @codengine [This python script](https://gitlab.com/david-arppe/regrowstumpssonsoftheforest) does it, but I haven't tested it.

Thanks for the link, that helps with the implementation.
