### ISSUE TITLE
Armor Slots numbering

### ISSUE THREAD

**Issue by PsyEng** [codengine/SOTFEdit#12]
I don´t know if this intended, but the numbering on the Armor page is a bit wired.
It counts 0, 1, 4, 5, 6, 7, 8, 9, 10, 11, so 2 and 3 aren´t there.
Also equipping it will result in a misplaced order ingame.
I added pictures, so it´s clear whats happening.
If I add all 10 pieces, it will show all 10 pieces correct ingame, so I think it autocorrcts the misplaced items.
I tried to find the code for it, but wasn´t able to get it, sry.

![SOTFEdit_v0 9 3_Armor](https://user-images.githubusercontent.com/21459890/233585931-4e3dd50c-ff68-4ab5-88ab-0a449accdd8d.png)
![SOTFEdit_v0 9 3_Armor_0-5](https://user-images.githubusercontent.com/21459890/233588925-e365509c-a478-4725-bdee-f337ed9c79ed.png)
![SOTFEdit_v0 9 3_Armor_0-5_ingame](https://user-images.githubusercontent.com/21459890/233588931-1714b62f-60cb-45c7-a2bc-eeebd5b60877.png)

**Comment by codengine** [comment]
Damn I have to fix it one day... So yeah the numbering is kind of "stupid" in that it is not continuous. So application works correctly.

Just try to fill all slots, your GUI ingame should be full :)

**Comment by codengine** [comment]
This is how it looks like when I manually number the Armor Slots from 0 to 9:
![grafik](https://user-images.githubusercontent.com/498798/233608365-7ffbc5ad-b1a4-4a22-98b9-d04011ecf0b6.png)

**Comment by codengine** [comment]
I've implemented an improvement which will be part of the next release.
