### ISSUE TITLE
If possible, add Dedicated Server save support

### ISSUE THREAD

**Issue by 64fanatic** [codengine/SOTFEdit#14]
I don't see much difference between client and dedicated saves, it would be nice to edit my dedicated server save data. Currently, if I try to change the location of my save data folder using the button in SOTFEdit, nothing happens when I press it. Cannot paste my server save file path either.

**Comment by codengine** [comment]
Hi, thx for your report. I'm going to have a look at the weekend what I can do.
Cheers.

**Comment by mindrunner** [comment]
works for me

**Comment by codengine** [comment]
So in general, savegames from dedicated servers work just fine, so I'm closing this request.
The only tricky part is that you have to transfer them locally somewhere, edit it with SOTFEdit and then transfer it back to your dedicated server.

I think it has to be shutdown before you do so.

**Comment by omayhemo** [comment]
SOTFEdit does not work on dedicated servers.  It doesn't report the saves correctly (positions, stats etc).  And when I saved a simple change from SOTFEdit, the entire build coordinates were wiped out.
