### ISSUE TITLE
Loading and changing savegames does not work with newest Update

### ISSUE THREAD

**Issue by Kev1n337** [codengine/SOTFEdit#15]
The newest version of SOTF saves its savegames in a zip folder and some of the values might have changed (e.g. there is no more "currentWeather" in WeatherSystemSaveData.json). Now when starting SOTFEdit, it does not propose the new savegames (only the ones saved with an older version of SOTF).

**Comment by codengine** [comment]
Hi, yeah they changed the save system quite a bit. I'm already working on a fix.

Kind regards

**Comment by codengine** [comment]
Should be fixed now:
https://github.com/codengine/SOTFEdit/releases/tag/v0.11.7

**Comment by codengine** [comment]
Please use this one instead. 0.11.7 had a bug.
https://github.com/codengine/SOTFEdit/releases/tag/v0.11.8
