### ISSUE TITLE
Save Dir Timestamp is Inaccurate

### ISSUE THREAD

**Issue by ButtKoWitz** [codengine/SOTFEdit#2]
The time stamps used on the displayed "SAVEGAMES" selections is inaccurate. The date/time is the dir's creation, not the timestamp of the latest saved file(s) contained in the dir.

Example: I created a New Save on "3/10/2023 12:17:17 PM"
Later I *overwrote* that save - the files in the dir are stamped at "3/15/2023 8:42 AM"

However, the displayed saved games in SOTFEDIT don't show the current timestamps of the *files* contained in the dirs.

Thanks!

**Comment by codengine** [comment]
Hi, I knew that this Issue would come up one day ;)
The thing is: I can not rely on the Timestamp in the save files alone as if a data file is modified, it would not be reflected in the "real" timestamp. Therefore I decided to use that one, but I'll think about using the last-write time only internally and for displaying I'll use the ingame timestamp.

Thanks for reporting though.

**Comment by ButtKoWitz** [comment]
Showing the file timestamp would certainly be appreciated, as otherwise I (we) have to manually fish though all saves looking for a particular save based on file date. Maybe just print the SaveDataThumbnail.png timestamp, seems simple enough as a failsafe file to use. Sure, someone *could* edit/replace the default png, but chances of that are pretty slim I'd wager.

Save Folder Created: *folder timestamp as is currently*
Last Save Appears to Be: *SaveDataThumbnail.png timestamp*

Appreciate your work!

**Comment by codengine** [comment]
The "real" timestamp is also inside the JSON files, so I can read the displayed TS from there.
The "last write" timestamp is just important because I wanted to prevent to overwrite external changes.

One of the main goals of this editor is to be "as less intrusive and damaging" as possible .)
