### ISSUE TITLE
Message: An item with the same key has already been added

### ISSUE THREAD

**Issue by bakedbeangaming** [codengine/SOTFEdit#20]
Hi, I just got this error on a new save Version: 0.11.14
Message: An item with the same key has already been added. Key: do you have any idea what could be causing it please

**Comment by codengine** [comment]
It has been reported already in Discord, I'll have a look.

**Comment by codengine** [comment]
The issue has been fixed in 0.11.15:
https://github.com/codengine/SOTFEdit/releases/tag/v0.11.15

**Comment by bakedbeangaming** [comment]
thank you
