### ISSUE TITLE
Pots get emptied

### ISSUE THREAD

**Issue by DiscordianKitty** [codengine/SOTFEdit#22]
Thank you for the editor! It's helped me make adjustments to my game difficulty settings.

And thank you for fixing planters! There's one more issue I've noticed - cooking pots on shelves are emptied when you use this editor. I like to collect different recipes and have them on the shelf, but I lose all their contents if I make a save edit. A pot in the player inventory is fine though. Is there any way to prevent that?

**Comment by codengine** [comment]
Hi,
I found and fixed the issue. Would be nice if you could test thoroughly if messing around with the storages does not cause any "damage".

During my test, the Cooking Pot kept its cooked recipe.

[SOTFEdit_CookingPot_fix.zip](https://github.com/codengine/SOTFEdit/files/13445188/SOTFEdit_CookingPot_fix.zip)

**Comment by DiscordianKitty** [comment]
Amazing! Just based on my initial testing, this seems to have worked flawlessly. I will keep testing and let you know if I run into any problems.

**Comment by walterst** [comment]
Hello,

Something similar probably affects the storage of modified arrows getting reverted to their base form. I'll try testing the above version sometime soon and see how it affects those.

**Comment by walterst** [comment]
The above version ([SOTFEdit_CookingPot_fix.zip](https://github.com/codengine/SOTFEdit/files/13445188/SOTFEdit_CookingPot_fix.zip)) does correctly save arrows as their modified types.

I suppose a nice feature would be able to see/specify the subtype of arrows in a stack/cooking pot contents

**Comment by codengine** [comment]
> The above version ([SOTFEdit_CookingPot_fix.zip](https://github.com/codengine/SOTFEdit/files/13445188/SOTFEdit_CookingPot_fix.zip)) does correctly save arrows as their modified types.
> 
> I suppose a nice feature would be able to see/specify the subtype of arrows in a stack/cooking pot contents

I'll keep that in mind, but I think I'm going to wait until it has left early access / beta because changes might happen.
E.g. they implemented the different ammo types and cooking pot over time, so changes in this item department might still happen.

Nevertheless I'm happy that this version also fixes this type of issue :)

**Comment by DiscordianKitty** [comment]
So far the cooking pots are working fine, but I just noticed Kelvin always unequips his space suit - it's also not in the drop-down options when choosing an outfit for him.

**Comment by codengine** [comment]
The bugfix has officially been released with [v0.11.18](https://github.com/codengine/SOTFEdit/releases/tag/v0.11.18).
