### ISSUE TITLE
ExtraStorage Support

### ISSUE THREAD

**Issue by LitPieper** [codengine/SOTFEdit#23]
There are a few options to increase your maximum storage for every item such as sticks, stones, resin, etc. though whenever you use SOTFEdit every overflowing item count will revert to vanilla max. I wish for SOTFEdit to only manipulate the numbers that one manually sets in the app.

**Comment by LitPieper** [comment]
> I must have missed this. When was this added and how can you enable the extra space?

The "options" are plugins, mods you can add to the game. It would be nice if I could still use the editor without losing the extra items I have gathered.

**Comment by codengine** [comment]
I'm probably going to add an option where it doesn't use the vanilla max value for the next release.

**Comment by codengine** [comment]
At long last, this has now been solved in 0.12.5:
https://github.com/codengine/SOTFEdit/releases/tag/v0.12.5
