### ISSUE TITLE
Cant't spawn Actors/NPCs

### ISSUE THREAD

**Issue by Driv28** [codengine/SOTFEdit#24]
I am unable to spawn any Actors or NPCs. I am using the interactive map. I can use all other features except for spawning NPCs and enemies.

**Comment by Driv28** [comment]
Ok i can see the NPC on the Interactive map but i can't see it in the game

**Comment by codengine** [comment]
Did you save and reload? Because it is not applied live.

**Comment by codengine** [comment]
No response, closed.
