### ISSUE TITLE
Blueprint not added to blueprint book

### ISSUE THREAD

**Issue by jusidama18** [codengine/SOTFEdit#26]
I tried add some blueprint like stick ladder blueprint to my multiplayer save game, but when i load that save it doesn't show up in blueprint book

**Comment by codengine** [comment]
Is it a locally hosted multiplayer game or do you use a dedicated server?

**Comment by codengine** [comment]
I can see the blueprint, I'll check if it is actually available in the game or not.
Some of the blueprints are just placeholder but not actually implemented. As far as I know I've need seen the stick ladder in action yet.
