### ISSUE TITLE
[Feature Request] item pickups one time use

### ISSUE THREAD

**Issue by The-Red-Menace** [codengine/SOTFEdit#28]
sons of the forest doesnt have a once use setting for loot you find scattered like rope bullets and food and I think for a better challege and those who like realism like me would love if you could implement a feature like this if possible (not sure how sotfedit worksfully)

**Comment by codengine** [comment]
I think this would not be possible. In custom mode however, you can let containers respawn if that helps?

**Comment by codengine** [comment]
Closing due to no response.
