### ISSUE TITLE
PlayerStateSaveData.json is not editable in the software

### ISSUE THREAD

**Issue by farhanulju** [codengine/SOTFEdit#29]
I played the game and didn't like the ending. So I didn't save after the completing the game, and restarted the launcher. When I reached the Cube room, I wasn't able to get in. 

So I edited the GameStateSaveData.json. But it still didn't work. 
PlayerStateSaveData.json needs to be edited and ExitHelicopter and data before that needs to be removed. But editing isn't possible with the software. 

Possible fix: 
edit option for ach data in PlayerStateSaveData.json  in the software

**Comment by codengine** [comment]
It is possible to reset the game state by just removing the value or setting it here to 0:
![grafik](https://github.com/codengine/SOTFEdit/assets/498798/1b820acb-282a-4523-8ebc-05278a46bf64)

Does that solve your issue?

**Comment by codengine** [comment]
Closing due to no response.
