### ISSUE TITLE
Unable to detect save games

### ISSUE THREAD

**Issue by Cubly** [codengine/SOTFEdit#3]
Doesn't detect save files

Log: https://pastebin.com/v83xwV8s

**Comment by codengine** [comment]
Hi, is the detected path in general correct? Moreover, could you check if the path is read-only and who is the file owner?
Last but not least, could you try to run the editor as an Administrator?

**Comment by Cubly** [comment]
Hi, yeah the path is correct, my user is the owner and has all perms. Running as administrator had the same problem.

**Comment by Cubly** [comment]
That's the only thing in the log file I'm afraid.

**Comment by codengine** [comment]
Alright, I'll prepare a special debug version of the Application. It would be nice if you could use that executable and test it again. Very strange 🤔

**Comment by codengine** [comment]
[SOTFEdit_Debug.zip](https://github.com/codengine/SOTFEdit/files/10996463/SOTFEdit_Debug.zip)

Here you go. The exception not being logged was actually a bug on my end :)

**Comment by Cubly** [comment]
Got it now https://pastebin.com/Xu12sWhz

**Comment by codengine** [comment]
Ah I see the reason immediately. I'm using the directory name as a unique identifier for the savegame and did not expect them to be not unique. I'll fix it :) Thanks for reporting it.

**Comment by codengine** [comment]
One more thing: Could you paste the directory structure of your savegame directory, starting at C:\Users\x\AppData\LocalLow\Endnight\SonsOfTheForest\Saves?

**Comment by Cubly** [comment]
C:\Users\\<User\>\AppData\LocalLow\Endnight\SonsOfTheForest\Saves\\<SteamID\>\Multiplayer\\<SomeID\>\\*json files*
C:\Users\\<User\>\AppData\LocalLow\Endnight\SonsOfTheForest\Saves\\<SteamID\>\MultiplayerClient\\<SomeID\>\\*json files*

**Comment by codengine** [comment]
Ahhhh that makes total sense. I've not tested it with Multiplayer yet :)
I'm building a fixed version right now, would be nice if you could try it again when the build is done.

**Comment by Cubly** [comment]
Will do!

**Comment by codengine** [comment]
https://github.com/codengine/SOTFEdit/releases/tag/v0.3.1
There you go

**Comment by Cubly** [comment]
Works well now. Ty!

**Comment by codengine** [comment]
> Works well now. Ty!

Awesome. Thank you!
