### ISSUE TITLE
Weapon Racks 

### ISSUE THREAD

**Issue by DiscordianKitty** [codengine/SOTFEdit#30]
I've found that some items disappear from weapon racks sometimes after using SOTFEdit. The gold and red masks seem to disappear every time. I had a gold guitar disappear once but couldn't replicate it. I remember there being a similar issue with cooking pots on shelves before, maybe the same cause?

**Comment by codengine** [comment]
The item locations in storages is a bit "tricky" and I had a couple of issues with it already.

But I can have a look. You say that only weapon racks ar affected?

**Comment by DiscordianKitty** [comment]
From what I've seen. I was wondering if it's in part because they're buggy to begin with. The one consistent thing seems to be that red and gold masks always disappear. When I get time I can test with all items that can go on racks and let you know if I notice anything else.

**Comment by codengine** [comment]
The masks were in fact missing from the items that are allowed for storages. Thanks for reporting it. I've added it. In case you find more items, feel free to create a new ticket.

![grafik](https://github.com/codengine/SOTFEdit/assets/498798/334ebcb4-4d8c-4a9d-846c-dbf224f53782)

**Comment by codengine** [comment]
Fixed in this release: https://github.com/codengine/SOTFEdit/releases/tag/v0.12.3
