### ISSUE TITLE
Dress shown in wrong bunker

### ISSUE THREAD

**Issue by FBroy** [codengine/SOTFEdit#34]
The dress (clothing) is shown to be in the entertainment bunker (left side), see screenshot (item marked in red).
![image](https://github.com/codengine/SOTFEdit/assets/59142692/775b10b8-c048-429c-87e4-e5dd4b61f529)
![image](https://github.com/codengine/SOTFEdit/assets/59142692/d63167e8-283d-4a80-8715-c1fa0bc39f17)

However, the actual location of the dress is in the Luxury bunker on the far right.
![image](https://github.com/codengine/SOTFEdit/assets/59142692/55da62d7-d3b7-4b34-b658-b170256d068e)
![image](https://github.com/codengine/SOTFEdit/assets/59142692/a45de621-4710-4f31-b7c6-284bd8d3e3c6)

**Comment by codengine** [comment]
Good catch, thanks for reporting!
