### ISSUE TITLE
Kelvin dead :( 

### ISSUE THREAD

**Issue by max380** [codengine/SOTFEdit#36]
![kelvin](https://github.com/user-attachments/assets/4c7d79f3-d679-4d0e-9cc7-33625c702604)

**Comment by max380** [comment]
![Uploading kelvin.png…]()

**Comment by codengine** [comment]
Do you have multiple Kelvin's in your game? Because the editor only shows the first one that it finds.

**Comment by codengine** [comment]
Closing due to lack of response.
