### ISSUE TITLE
Wrong placed data.json prevents starting

### ISSUE THREAD

**Issue by Ravo92** [codengine/SOTFEdit#5]
data.json file was in root directory of SOFTEdit instead of data\data.json. See log file.
[logs-2023-03-26.txt](https://github.com/codengine/SOTFEdit/files/11070503/logs-2023-03-26.txt)

**Comment by codengine** [comment]
This is strange. I just downloaded the zip file from github and it does indeed have the data.json at the right place:
![grafik](https://user-images.githubusercontent.com/498798/227751049-b29ab5ef-e404-4d23-aca5-36c4ce47a194.png)

Is it possible that your path is just too long? Windows has a certain limit. Could you try to download it again and decompress it to a different location?

**Comment by Ravo92** [comment]
Its more like.. im using the "r2modman-3.1.39" where i did download your mod. So, maybe its wrong on their side?

**Comment by codengine** [comment]
Hm it's possible. So does the version from github work for you? Because I've basically uploaded the same ZIP file everywhere. My best guess is that the pathname is just too long

**Comment by codengine** [comment]
I think I found something:
https://github.com/ebkr/r2modmanPlus/issues/944

So it is indeed their way of handling zip files. I'll have a look tomorrow at that I can do.

**Comment by Ravo92** [comment]
Yes, im 100% certain its because of the flat file hierachy.

**Comment by codengine** [comment]
BTW. This is not a BeoinEx Plugin but rather a standalone application. Does that make any difference in regards to your report? Is it even the right way to install it like the way you did?

**Comment by Ravo92** [comment]
Hey, i think its up to you if installing the tool via modmanPlus is the right way anyway. I installed it via the program and saw its a .net exe in appdata which cant be started as a real "mod" via game. So i executed your exe after install just to see the file hierarchy for the json is wrong and i corrected it manually anyway. I think this issue can be solved if you make it either flat or dismiss it from this mod tool. I just think about other people who could potentionally have the same problem and cant read .net exceptions.

**Comment by codengine** [comment]
To be honest, extracting zip archives to a flat structure because of legacy reasons doesn't justify that I change the whole application structure. In my opinion it's a bug in r2modman

I'll try to find another way.

**Comment by Ravo92** [comment]
Understandable. For now ill use the "standalone" tool directly from your github.

**Comment by codengine** [comment]
I raised a feature request on their github:
https://github.com/ebkr/r2modmanPlus/issues/997

Let's see what they respond
