### ISSUE TITLE
Inventory > Unassigned Items Not Clearing/Reinitializing

### ISSUE THREAD

**Issue by M249-M4A1** [codengine/SOTFEdit#6]
The **Inventory > Unassigned Items** list will display duplicate values when loading multiple saves or clicking the **File > Reload Current Savegame** function

![01](https://user-images.githubusercontent.com/11793447/229380230-c084514d-1505-40b8-8b5d-166c330ba16d.PNG)

**Comment by codengine** [comment]
Thanks for the report, I will have a look.
