### ISSUE TITLE
system exception

### ISSUE THREAD

**Issue by my4b** [codengine/SOTFEdit#7]
probably related to the fresh game update.  
anyway I get this one. 

https://pastebin.com/hhDiX8tj

**Comment by codengine** [comment]
Hi, yes I've found and fixed the issue already. I'm currently adding some new ItemIds and will release a new version later this evening. Thanks for reporting.

**Comment by codengine** [comment]
v0.8.2 contains the fix as well as some new stuff from Patch 03.

**Comment by my4b** [comment]
good job. I can confirmi it's completely fixed
